#!/bin/csh
#$ -M <email>
#$ -m a
#$ -r y
#$ -q long
#$ -pe smp 4
#$ -N RunR_HETobs
#$ -t 1-32
set path = ( $path /R/ )

#This job file submits separate jobs for each population
set names = ( "POP_1.1" "POP_1.2" "POP_1.3" "POP_2.1" "POP_2.2" "POP_2.3" "POP_2.4" "POP_2.5" "POP_2.6" "POP_2.7" "POP_2.8" "POP_3.1" "POP_3.2" "POP_3.3" "POP_4.1" "POP_4.2" "POP_4.3" "POP_4.4" "POP_4.5" "POP_4.6" "POP_4.7" "POP_4.8" "POP_4.9" "POP_5.1" "POP_5.2" "POP_5.3" "POP_6.1" "POP_7.1" "POP_7.2" "POP_7.3" "POP_7.4" "POP_8.1" )


module load bio/R/3.4.0
setenv R_LIBS /Rlibs/
R -f HETobs_loop_$names[${SGE_TASK_ID}].R

