#!/bin/csh
#$ -M sryan6@nd.edu
#$ -m e
#$ -r y
#$ -q long
#$ -pe smp 16
#$ -N RunCombineGVCFs_batch11
set path = ( $path /afs/crc.nd.edu/group/hellmann/hlm_3/GenomeAnalysisTK-3.8-0-ge9d806836 )

 java -jar -Xmx32g GenomeAnalysisTK.jar \
   -T CombineGVCFs \
   -R ../Genomes/Pieris_rapae_assembly_v2/Pieris_assembly_v2.fa \
   --variant ./GVCFs/Pr_2065_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1946_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_700_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1125_HiSeq2_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_699_HiSeq1_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_281_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1_HiSeq1_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1509_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_417_HiSeq1_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1180_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_919_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_255_HiSeq1_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1881_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1882_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1883_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1884_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1885_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_2017_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_2018_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_2019_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_202_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_2020_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_2021_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_2022_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_2023_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_2024_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_2025_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_2026_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_2027_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1891_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1892_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1895_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1896_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1899_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1886_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1887_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1888_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1889_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1890_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1901_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1910_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1911_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1912_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1915_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1916_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1917_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1918_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1919_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_1920_merged_rawLikelihoods.g.vcf.gz \
   --variant ./GVCFs/Pr_891_merged_rawLikelihoods.g.vcf.gz \
   -o PierisProject_cohort_11.g.vcf
